### ISSUE TITLE
Update Theme for Buttons

### ISSUE THREAD

**Issue by VincentLeighton** [Wolven531/simple-cra-app#57]
Update the application Theme to add shadow to the button and button text, as well as use contrastText in the existing Theme for the black background effect.

![image](https://user-images.githubusercontent.com/1578197/126245133-d7f152f1-33c8-40b6-ab1f-e1a3c94a679a.png)

**Comment by Deepak8717** [comment]
Hello, I can do it as long as it is just the css part.  what are the three boxes ? are those text boxes or just labels with random data ?

**Comment by Wolven531** [comment]
@Deepak8717 They are the displayed results from hitting the API; each one is a different value from the response. Currently, the labels and values are displayed w/ MUI's Typography element. Those labels and values are not the focus here, though.

This ticket is to update the app-wide MUI theme so that by default, the app's primary buttons look like the button featured in this screenshot (button w/ glowing text, black fill, green font, etc.)
